#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

export HOMEBREW_CASK_OPTS="--appdir=/Applications" # Set install location for brew-cask
export TERM=xterm-256color
export TMUX_POWERLINE_SEG_WEATHER_LOCATION="2490383"
export TMUX_POWERLINE_SEG_WEATHER_UNIT='f'
export TMUX_POWERLINE_SEG_NOW_PLAYING_MUSIC_PLAYER="rdio"

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi
