#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'
export HOMEBREW_CASK_OPTS="--appdir=/Applications" # Set install location for brew-cask
export TERM=xterm-256color
export TMUX_POWERLINE_SEG_WEATHER_LOCATION="2503523"
export TMUX_POWERLINE_SEG_WEATHER_UNIT='f'
export TMUX_POWERLINE_SEG_NOW_PLAYING_MUSIC_PLAYER="rdio"

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi



#
# Paths
#

typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  /usr/local/share/python
  /usr/local/share/npm/bin
  /usr/local/bin/elixir/bin
  /usr/local/heroku/bin
  /Applications/Postgres.app/Contents/MacOS/bin
  ~/Developer/Code/go/bin
  /Applications/Racket v5.3.6/bin
  $path
)

export GOPATH=$HOME/Developer/Code/go # Google Go Path

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
if (( $+commands[lesspipe.sh] )); then
  export LESSOPEN='| /usr/bin/env lesspipe.sh %s 2>&-'
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$USER"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"
if [[ ! -d "$TMPPREFIX" ]]; then
  mkdir -p "$TMPPREFIX"
fi

# Make vim work with RVM
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"  # This loads RVM into a shell session.
