#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
eval "$(tmuxifier init -)"

# Tmuxifier layouts
export TMUXIFIER_LAYOUT_PATH="$HOME/Developer/Code/nanofiles/tmux-layouts"

# Vagrant environment variables
export VAGRANT_HOME=/Volumes/Media/vagrant
export VAGRANT_VMWARE_CLONE_DIRECTORY=/Volumes/Media/vagrant/vmware_clone_dir

source ~/.zprezto/submodules/k/k.sh
source `brew --prefix`/etc/profile.d/z.sh
source ~/.aliases
